# -*- coding: utf-8 -*-
"""paralellogramme.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a03JOiUl-CDwYUhRT-QkP9eDOBjf9zUW

Zeichne das Prallelogramm ABCD in eine Koordinatensystem mit der Einheit 1 cm ein. Bestimme seinen Umfang und seinen Flächeninhalt.
"""

import matplotlib.pyplot as plt
import numpy as np
 
 
x = [1,7,10,4,1]
y = [1,1,5,5,1]
 
plt.plot (x,y)
plt.show
a = (x[1])-(x[0])
ha = (y[2])-(y[1])
A = a * ha
A = str(A)
print (" Die Fläche des Paralellorgramms ist = "  +A+" cm²" )
 
seite_a = (x[2])-(x[1])
seite_b = ha
 
seite_c = (seite_a**2)+(seite_b**2)
 
 
b = np.sqrt (seite_c)
 
U = (2*a)+(2*b)
U = str (U)
print (" Der Umfang des Paralellorgramms ist = "  +U+" cm" )